### ISSUE TITLE
Launch/Close Program with Game

### ISSUE THREAD

**Issue by Dave247** [Haato3o/HunterPy#1]
A possible feature could be for the app to be able to launch the game either automatically or by clicking a button in the dashboard, as well as having the program terminate itself when it detects the game is no longer running.

In regards to the program launching the game for you, there would need to have the option for the user to specify their game install location, and/or have the ability to parse arguments through the program, such as the example I made here for another game using pypresence.
https://github.com/Lasa2/Elite-Dangerous-Rich-Presence/issues/6#issue-520594146

**Comment by haato3o** [comment]
I'm not supporting HunterPy anymore because I decided to move to C# instead of Python, but I might add that feature on the [C# version](https://github.com/Haato3o/HunterPie).
